jobs:
  use_api:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GSO_TOKEN_TEST }}
        run: |
          gh api /octocat
          
          
name: Backup Issues and Milestones

on:
  workflow_dispatch:

env:
  TEST_TOKEN: ${{ secrets.TEST_TOKEN }}

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Check Token
      run: |
        curl -v -H "Authorization: token $TEST_TOKEN" https://api.github.com/user/issues
